name: ControlFront Scan

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run ControlFront scan (CI mode)
        run: npx -y @controlfront/cli@latest scan
        env:
          NEXT_PUBLIC_APP_URL: https://app.controlfront.io
          CF_ORG_ID: 446b215d-09c3-4d4f-9217-903d5bd7e8ca
          CF_PROJECT_ID: 3e6d8d65-f688-44ef-9051-33c35439ae27
          CF_CI_MODE: "true"
          CF_INGEST_TOKEN: pzHFBseIF98K-pZAyDI-nBPUHTpqi-YCwyzz56m_g_A
