name: ControlFront Scan

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run ControlFront scan (CI mode)
        run: npx -y @controlfront/cli@latest scan
        env:
          NEXT_PUBLIC_APP_URL: https://cf-dev-x8a9k2h1r7v3pzq5.ngrok.app
          CF_ORG_ID: e77d8bf-4728-4ada-9432-aace32f5ab2
          CF_PROJECT_ID: 05bac0a5-1c0b-4ba8-a87c-1f0df59b2ff3
          CF_CI_MODE: "true"
          CF_INGEST_TOKEN: ${{ secrets.CF_INGEST_TOKEN }}
